### ISSUE TITLE
 Problems with saving projects and mods

### ISSUE THREAD

**Issue by DavoTriskele** [paulov-t/FrostbiteModdingTool#87]
Hi Pau and thanks for the immense work you bring to FIFA.
I'm having a big problem with FMT.
Initially I was able to create mods, albeit with some difficulty. Project files and mods were saved and opened by the tool.
Suddenly, for at least 1 week, I have no longer been able to reload the created jobs into the tool. I'm trying several times also creating new small works. The tool does not open the project and does not load the mod.
The files I save have a variable weight of several hundred MB. I think it means that the projects are actually saved. What can it be? What am I doing wrong? Obviously I start the FMT as administrator.
Thank you.

**Comment by DavoTriskele** [comment]
I usually try to load the project from the tool. A few moments ago I tried to create a minimal project to test saving and I tried to start it by double clicking on the file. The FMT was closed.
An error popup opened. I'll post it below.

Newtonsoft.Json.JsonSerializationException: Unexpected end when setting MergedModList's value. Path 'MergedModList', line 1, position 1822.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at FrostySdk.ModsAndProjects.Projects.FMTProject.Read(Stream stream, FMTProject project)
   at FrostySdk.ModsAndProjects.Projects.FMTProject.Read(String filePath)
   at FMT.MainWindow.HandleAppArguments()
   at FMT.MainWindow.MainWindow_Loaded(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

**Comment by DavoTriskele** [comment]
mods created by me.
I'm trying to load the project file and it doesn't load. I also tried loading the mod with the editor and it loads nothing.
In the last test I simply loaded 1 kit and the fifasplesh and it doesn't reload it

**Comment by DavoTriskele** [comment]
I checked the wiki section but I don't think I found the solution to the problem. I searched in all the sections present.
The EA Desktop section explains how to launch the mod with the EA app.
My problem is another. The created project is not read. I have created projects of over 200Mb but I cannot continue working on them because when I try to open them they are not read. In some cases I am given the WARNING with the error.
Mods created together with the project are not opened by the tool.
If you want I can also send you my project files. I can also create a new one now and send it to you.
Maybe I didn't find the solution to the problem on the wiki.
Again, a few weeks ago I managed to create an initial Triskele Mod project that got corrupted in the next save. From that moment on I was no longer able to create projects and mods :,(

**Comment by DavoTriskele** [comment]
https://drive.google.com/file/d/1PoL7deV21grNcdFvd0XCrZXRobbNKH7m/view?usp=sharing

**Comment by DavoTriskele** [comment]
Not receiving a response of any kind, after about a week I deleted the file on my drive. I imagine the amount of work you have but I thought a week would be enough to receive at least one response.
For now I'm working with the tools that allow you to work. I can't afford to sit still with the mod.
The more stable tools there are, the better for everyone. If you can fix the tool it's a wonderful thing for the whole community. Removing the monopoly is always wonderful news in any field.
I will have no problem using and having your work used.
I'm already having my Italian community download the tool.
In addition to that problem I told you, I think you also need to fix something else, if I may give you some advice, for example the possibility of separating the 2 tools (mod and editor) into 2 different platforms. Those who work with mods may need to work with the open project while they are with the newly launched game (the editor launch didn't even work for me).
If you need anything, write to me. I'll leave you my direct email
triskeleesports@gmail.com

Thank you always for your work
