### ISSUE TITLE
Exception raise when building Fc24 game cache

### ISSUE THREAD

**Issue by LycenYao** [paulov-t/FrostbiteModdingTool#88]
Version: 24.0.8685.36478
Game: EASFC 24(steam version)

---------------------------

---------------------------
System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.

   at System.Security.Cryptography.SymmetricPadding.GetPaddingLength(ReadOnlySpan`1 block, PaddingMode paddingMode, Int32 blockSize)

   at System.Security.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(ReadOnlySpan`1 inputBuffer, Span`1 outputBuffer)

   at System.Security.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)

   at System.Security.Cryptography.UniversalCryptoTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)

   at System.Security.Cryptography.CryptoStream.ReadAsyncCore(Memory`1 buffer, CancellationToken cancellationToken, Boolean useAsync)

   at System.Security.Cryptography.CryptoStream.Read(Byte[] buffer, Int32 offset, Int32 count)

   at System.Security.Cryptography.CryptoStream.CopyTo(Stream destination, Int32 bufferSize)

   at FrostySdk.FileSystem.ReadLocaleIni()

   at FrostySdk.Frostbite.IO.LocaleIniManager.Load()

   at FrostySdk.Frostbite.IO.LocaleIniManager..ctor()

   at FrostySdk.Managers.AssetManager..ctor()

   at FrostySdk.Managers.AssetManager..ctor(ILogger& inLogger)

   at FrostySdk.Frostbite.CacheManager.Load(ReadOnlySpan`1 gameLocation, ILogger logger, Boolean loadSDK, Boolean forceDeleteOfOld)

   at FrostySdk.Frostbite.CacheManager.<>c__DisplayClass21_0.<LoadDataAsync>b__0()

   at System.Threading.Tasks.Task`1.InnerInvoke()

   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)

--- End of stack trace from previous location ---

   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

--- End of stack trace from previous location ---

   at FrostySdk.Frostbite.CacheManager.LoadDataAsync(String GameVersion, String gameLocation, ILogger logger, Boolean forceDeleteOfOld, Boolean loadSDK)

   at FMT.Pages.Common.CacheManagerControl.Rebuild(CancellationToken cancellationToken, Boolean forceRebuild)

   at FrostbiteModdingUI.Windows.DefaultEditor.DefaultEditor_Loaded(Object sender, RoutedEventArgs e)

   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.DispatcherOperation.InvokeImpl()

   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

--- End of stack trace from previous location ---

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Windows.Threading.DispatcherOperation.Invoke()

   at System.Windows.Threading.Dispatcher.ProcessQueue()

   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)

   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)

   at System.Windows.Application.RunDispatcher(Object ignore)

   at System.Windows.Application.RunInternal(Window window)

   at FMT.App.Main()

**Comment by karlkarltong** [comment]
same problem here!

Version: 24.0.8685.36478
Game: FC 24(steam version)

**Comment by LycenYao** [comment]
@paulov-t 
Today the exception didn't show up, but mod seems not appplied to the game properly

ps. I think the locale.ini may cause the problem. Today I reverted it back and the error disappeared.

**Comment by karlkarltong** [comment]
> @paulov-t I think the locale.ini may cause the problem. Today I reverted it back and the error disappeared.

yea! same here, problem solved. Thanks!
